format: sql
sets:
    patients:
        _attributes: { count: 5 }
        first_name: { type: string, min_length: 2, max_length: 16 }
        last_name: { type: string, min_length: 2, max_length: 16 }
        birth_at: { type: date, min: 1900-01-01, max: 2006-12-31 }
        pesel: { type: pesel }
        country: { type: entity, from: countries_pl }
        sex: { type: fixed, value: m }
        created_at: { type: ruby, code: 'DateTime.now()' }
    visits:
        _attributes: { count: 8 }
        patient_id: { type: number, min: 1, max: 100 }
        description: { type: text }

