format: sql
sets:
    patients:
        _attributes: { count: 40 }
        # Prefix test
        street: { type: entity, from: streets_pl, prefix: { type: fixed, value: 'ul. ' } }
        # Double suffix test
        company_name: { type: string, min_length: 2, max_length: 6, suffix: { type: fixed, value: '!', suffix: { type: code, code: 'rand(7).times.collect { "1" }.join("")' } } }
        # Suffix for integer
        application_id: { type: number, suffix: { type: fixed, value: 'a' } }
        last_activity: { type: datetime, min: '2000-01-01 00:00:00', null_density: 0.1 }
        firstname: { type: entity, from: first_names_pl }
        lastname: { type: entity, from: last_names_pl }
        birthday_at: { type: date, max: '2003-12-31' }
        pesel: { type: pesel, fields_as_args: [birthday_at] }
        country: { type: entity, from: countries_pl }
        active: { type: fixed, value: true }
        created_at: { type: code, code: 'DateTime.now()' }
    visits:
        _attributes: { count: 20 }
        patient_id: { type: number, min: 2, max: 5 }
        description: { type: text }

