format: sql
sets:
    patients:
        _attributes: { count: 200 }
        application_id: { type: fixed, value: 3 }
        name1: { type: entity, from: first_names_pl }
        lastname1: { type: entity, from: last_names_pl }
        birthday_at: { type: date, min: 1900-01-01, max: 2006-12-31 }
        pesel: { type: pesel, fields_as_args: [birthday_at] }
#       country: { type: entity, from: countries_pl }
        gender_id: { type: number, min: 1, max: 2 }
        active: { type: fixed, value: true }
        created_at: { type: code, code: 'DateTime.now()' }
    visits:
        _attributes: { count: 1 }
        patient_id: { type: number, min: 2, max: 5 }
        description: { type: text }

